import c1 from './assets/glock/c1.wav'
import cH1 from './assets/glock/c-1.wav'
import d1 from './assets/glock/d1.wav'
import dH1 from './assets/glock/d-1.wav'
import e1 from './assets/glock/e1.wav'
import f1 from './assets/glock/f1.wav'
import fH1 from './assets/glock/f-1.wav'
import g1 from './assets/glock/g1.wav'
import gH1 from './assets/glock/g-1.wav'
import a2 from './assets/glock/a2.wav'
import aH2 from './assets/glock/a-2.wav'
import b2 from './assets/glock/b2.wav'
import c2 from './assets/glock/c2.wav'
import cH2 from './assets/glock/c-2.wav'
import d2 from './assets/glock/d2.wav'
import dH2 from './assets/glock/d-2.wav'
import e2 from './assets/glock/e2.wav'

export const glock = [ c1, cH1, d1, dH1, e1, f1, fH1, g1, gH1, a2, aH2, b2, c2, cH2, d2, dH2, e2 ];
